import Image from 'next/image'
import { Analytics } from '@vercel/analytics/next'
import './globals.css'

export const metadata = {
  metadataBase: new URL('https://onlinenikahservices.com'),
  title: { default: 'Online Nikah Services | Trusted Remote Nikah Guidance', template: '%s | Online Nikah Services' },
  description: 'Professional guidance for couples arranging an online Nikah, document review and Pakistan-based registration assistance.',
  alternates: { canonical: '/' },
  openGraph: { type: 'website', siteName: 'Online Nikah Services', title: 'Online Nikah Services', description: 'Thoughtful, practical guidance for your Nikah journey.' },
}
export const viewport = { colorScheme: 'light', themeColor: '#f7f4ed', userScalable: true }
export default function RootLayout({ children }) {
  return <html lang="en-GB"><body>{children}{process.env.NODE_ENV === 'production' && <Analytics />}</body></html>
}

export const siteConfig = {
  phone: '+92 333 1127830', whatsapp: 'https://wa.me/923331127830',
  cities: { Karachi: '+92 333 1127830', Lahore: '+92 333 1127835', Islamabad: '+92 333 1127836', Rawalpindi: '+92 333 1127831' }
}

export function jsonLd(data) { return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }} /> }

export const organisationSchema = { '@context': 'https://schema.org', '@type': 'Organisation', name: 'Online Nikah Services', url: 'https://onlinenikahservices.com', description: 'Online Nikah guidance, document review and Pakistan-based registration assistance.' }

export const websiteSchema = { '@context': 'https://schema.org', '@type': 'WebSite', name: 'Online Nikah Services', url: 'https://onlinenikahservices.com' }

export const countries = [
  ['Pakistan','/pakistan/'], ['United Arab Emirates','/united-arab-emirates/'], ['Saudi Arabia','/saudi-arabia/'], ['Qatar','/qatar/'], ['United Kingdom','/united-kingdom/'], ['United States','/united-states/'], ['Canada','/canada/']
]

export const services = [['Online Nikah ceremony','/our-services/'], ['Document review','/our-services/'], ['Registration assistance','/our-services/'], ['Overseas document use','/our-services/']]

export function breadcrumbSchema(items) { return { '@context':'https://schema.org', '@type':'BreadcrumbList', itemListElement: items.map((item, index) => ({ '@type':'ListItem', position:index+1, name:item[0], item:`https://onlinenikahservices.com${item[1]}` })) } }

export function PageJsonLd({ breadcrumb, service, faq }) { return <>{jsonLd(organisationSchema)}{jsonLd(websiteSchema)}{breadcrumb && jsonLd(breadcrumbSchema(breadcrumb))}{service && jsonLd({ '@context':'https://schema.org', '@type':'Service', name:service, provider:organisationSchema })}{faq && jsonLd({ '@context':'https://schema.org', '@type':'FAQPage', mainEntity:faq.map(x => ({ '@type':'Question', name:x[0], acceptedAnswer:{ '@type':'Answer', text:x[1] } }))})}</> }

export function makeMetadata(title, description, path) { return { title, description, alternates:{canonical:path}, openGraph:{title, description, url:path, type:'website'} } }

export function whatsappLink(message='Hello, I would like to ask about your online Nikah services.') { return `${siteConfig.whatsapp}?text=${encodeURIComponent(message)}` }

export function safeCityWhatsApp(city) { const numbers = { Karachi:'923331127830', Lahore:'923331127835', Islamabad:'923331127836', Rawalpindi:'923331127831' }; return `https://wa.me/${numbers[city] || '923331127830'}` }

export function SectionTitle({ eyebrow, title, children, light=false }) { return <div className={`section-title ${light ? 'section-title-light' : ''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children && <p className="section-lead">{children}</p>}</div> }

export function CTA({ href=siteConfig.whatsapp, children='Start a conversation', outline=false }) { return <a className={`button ${outline ? 'button-outline' : ''}`} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined}>{children}<span aria-hidden="true">↗</span></a> }

export function Footer() { return <footer className="footer"><div className="footer-inner"><div><a className="brand footer-brand" href="/">Online <em>Nikah</em><br/><span>Services</span></a><p className="footer-note">Thoughtful guidance for couples arranging their Nikah across borders.</p></div><div><p className="footer-heading">Explore</p><a href="/our-services/">Our services</a><a href="/pakistan/">Nikah in Pakistan</a><a href="/blogs/">Helpful guides</a><a href="/about-us/">About us</a></div><div><p className="footer-heading">Contact</p><a href="tel:+923331127830">{siteConfig.phone}</a><a href={siteConfig.whatsapp}>WhatsApp us</a><a href="/contact-us/">Send an enquiry</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Online Nikah Services</span><span>Information is general guidance, not legal advice.</span></div></footer> }

export function PageFrame({ children, dark=false }) { return <>{children}<Footer/><a className="mobile-action" href={siteConfig.whatsapp}>WhatsApp us <span>↗</span></a></> }

export function Hero({ eyebrow='ONLINE NIKAH SERVICES', title, children, image='/hero-nikah.png', imageAlt='A modest Muslim couple preparing for their Nikah ceremony', actions }) { return <section className="hero"><div className="hero-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><div className="hero-description">{children}</div><div className="hero-actions">{actions}</div></div><div className="hero-image"><Image src={image} alt={imageAlt} fill priority sizes="(max-width: 800px) 100vw, 50vw" className="hero-image-media" /><span className="image-caption">Respectful. Remote. Considered.</span></div></section> }

export function SupportingImages() { return <section className="supporting-images" aria-label="Nikah ceremony details"><figure><Image src="/support-signing.png" alt="Hands signing a Nikah document with a fountain pen" width={900} height={675} loading="lazy" sizes="(max-width: 800px) 100vw, 33vw" /><figcaption>Nikah Nama signing</figcaption></figure><figure><Image src="/support-rings.png" alt="Simple wedding rings beside a Nikah document" width={900} height={675} loading="lazy" sizes="(max-width: 800px) 100vw, 33vw" /><figcaption>The details matter</figcaption></figure><figure><Image src="/support-video-call.png" alt="A remote Nikah ceremony coordinated over a laptop video call" width={900} height={675} loading="lazy" sizes="(max-width: 800px) 100vw, 33vw" /><figcaption>Remote coordination</figcaption></figure></section> }

export function FAQ({ items }) { return <div className="faq-list">{items.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div> }

export function Header() { return <header className="site-header"><div className="header-inner"><a className="brand" href="/">Online <em>Nikah</em><br/><span>Services</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="/">Home</a><div className="nav-menu"><button type="button">Our Services <span>⌄</span></button><div className="nav-dropdown">{services.map(([name, href]) => <a key={name} href={href}>{name}</a>)}</div></div><div className="nav-menu"><button type="button">Countries <span>⌄</span></button><div className="nav-dropdown countries-menu">{countries.map(([name, href]) => <a key={name} href={href}>{name}</a>)}</div></div><a href="/blogs/">Blog</a><a href="/about-us/">About Us</a><a href="/contact-us/">Contact Us</a></nav><a className="header-whatsapp" href={siteConfig.whatsapp}>WhatsApp <span>↗</span></a><details className="mobile-nav"><summary aria-label="Open menu">☰</summary><nav>{[['Home','/'],['Our services','/our-services/'],['Pakistan','/pakistan/'],['Other countries','#countries'],['Blog','/blogs/'],['About us','/about-us/'],['Contact us','/contact-us/']].map(([n,h]) => <a key={n} href={h}>{n}</a>)}</nav></details></div></header> }

export function Layout({ children }) { return <PageFrame><Header />{children}</PageFrame> }

export function CountryGrid() { return <div className="country-grid">{countries.map(([name, href], i) => <a className="country-tile" href={href} key={name}><span className="country-number">0{i+1}</span><span><strong>{name}</strong><small>Explore service guidance</small></span><span className="arrow">↗</span></a>)}</div> }

export function ContactForm() { return <form className="contact-form" action={siteConfig.whatsapp} target="_blank"><div className="form-grid"><label>Your name<input required name="name" placeholder="Full name" /></label><label>Your country<input required name="country" placeholder="Where do you live?" /></label></div><label>WhatsApp number<input required name="phone" placeholder="Include country code" /></label><label>How can we help?<textarea required name="message" rows="5" placeholder="Tell us briefly about your situation" /></label><button className="button" type="submit">Continue to WhatsApp <span>↗</span></button><p className="form-note">Your details will open in WhatsApp for you to review and send. We do not request identity document uploads through this form.</p></form> }

export const countryData = {
 'united-arab-emirates': { name:'United Arab Emirates', short:'the UAE', intro:'Practical coordination for residents of the UAE considering a Nikah arranged with Pakistan-based support.', image:'/hero-uae.png', angle:'Your ceremony, planned around distance and time zones.' },
 'saudi-arabia': { name:'Saudi Arabia', short:'Saudi Arabia', intro:'A considered starting point for couples in Saudi Arabia who need clarity on an online Nikah and the documents that may follow.', image:'/hero-saudi.png', angle:'Begin with the right questions and a clear document path.' },
 'qatar': { name:'Qatar', short:'Qatar', intro:'Remote Nikah guidance for residents of Qatar, with careful attention to identity, consent, witnesses and intended document use.', image:'/hero-qatar.png', angle:'A respectful process for couples arranging their Nikah remotely.' },
 'united-kingdom': { name:'United Kingdom', short:'the UK', intro:'Clear, careful guidance for couples in the UK exploring an online Nikah with Pakistan-based arrangements.', image:'/hero-uk.png', angle:'Understand what a Nikah is — and what it is not — in your circumstances.' },
 'united-states': { name:'United States', short:'the United States', intro:'Remote planning support for couples in the United States who want to explore a Nikah ceremony and possible Pakistan-based registration steps.', image:'/hero-usa.png', angle:'A grounded conversation before you commit to a process.' },
 'canada': { name:'Canada', short:'Canada', intro:'A practical guide for residents of Canada considering an online Nikah, document review and next steps.', image:'/hero-canada.png', angle:'Plan your Nikah with care, clarity and realistic expectations.' }
}

export const countryFaq = (name) => [[`Can a couple in ${name} attend remotely?`, 'Remote participation may be possible depending on the proposed ceremony format, identity checks, witnesses and the requirements of the people conducting the Nikah. We review the details before confirming a route.'],['Will an online Nikah automatically be recognised where I live?','No automatic recognition is promised. A religious ceremony, statutory marriage registration and use of documents abroad are separate matters; the relevant authority or adviser in your destination country may need to assess your circumstances.'],['What should we prepare first?','Start with both parties’ identity details, current locations, preferred date, witness availability, Mehr discussion and the intended use of any documents. We can then explain the next practical steps.'],['How do fees and timing work?','Fees and timings depend on the ceremony format, document needs, translation or attestation requests and availability. We provide a fee enquiry after understanding the scope rather than publishing a misleading one-size-fits-all figure.']]

export const pakistanFaq = [['Can a Nikah be arranged while one or both parties are abroad?','Remote arrangements may be possible after an eligibility and document review. The ceremony format, witnesses and registration route must be discussed before any date is confirmed.'],['Do you provide an office in every Pakistani city?','No. We distinguish remote nationwide coverage from any physical office information. Please contact us for the current arrangements relevant to your case.'],['Is the ceremony the same as legal registration?','No. Nikah solemnisation, statutory registration and later translation, attestation or overseas use are different stages. Each may have its own requirements.'],['How do I ask about fees?','Send your locations, preferred date, document needs and intended use through WhatsApp. We will review the enquiry and explain the likely scope before quoting.']]

export function CountryBody({ data, isPakistan=false }) { const faq = isPakistan ? pakistanFaq : countryFaq(data.name); return <><section className="intro-band"><div><p className="eyebrow">A considered starting point</p><h2>{isPakistan ? 'A remote service with local context.' : data.angle}</h2></div><p>{isPakistan ? 'Our role is to help you understand the practical sequence: eligibility review, ceremony planning, witnesses and Mehr, followed where appropriate by registration assistance and document-use guidance.' : data.intro}</p></section><section className="content-section split-section"><div><p className="eyebrow">01 / Scope</p><h2>What we can help you understand</h2></div><div className="prose"><p>Every enquiry starts with a private conversation about where each person lives, the proposed ceremony, identity and consent, witnesses, Mehr and what you need the documents for. This helps avoid treating a religious ceremony and a government process as interchangeable.</p><p>Where Pakistan-based arrangements are relevant, we can explain the likely sequence and which details need checking. Translation, attestation, immigration evidence and recognition in another country are separate, case-specific steps. We do not promise automatic validity or acceptance by any authority.</p><a className="text-link" href="/contact-us/">Ask about your circumstances <span>↗</span></a></div></section><SupportingImages/><section className="process-section"><div className="section-title"><p className="eyebrow">02 / The process</p><h2>Clarity before a ceremony date.</h2></div><div className="process-grid">{[['01','Share the outline','Tell us where you both live, your preferred timing and what you hope to achieve.'],['02','Review the essentials','We discuss identity, consent, witnesses, Mehr and any document or translation questions.'],['03','Agree the route','You receive a clear explanation of the ceremony and any separate registration or document steps.'],['04','Prepare carefully','We coordinate the agreed arrangements and keep the distinction between each stage visible.']].map(x => <div className="process-item" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section><section className="content-section faq-section"><div className="section-title"><p className="eyebrow">03 / Questions</p><h2>Useful answers for {isPakistan ? 'Pakistan' : data.name} residents.</h2></div><FAQ items={faq} /></section><section className="cta-band"><p className="eyebrow">Next step</p><h2>Tell us what you need to arrange.</h2><p>We will help you separate the ceremony, registration and document-use questions before you decide how to proceed.</p><CTA href={whatsappLink(`Hello, I live in ${isPakistan ? 'Pakistan' : data.name} and would like to ask about online Nikah services.`)} children="Ask on WhatsApp" /></section></> }

export function CountryPage({ data, isPakistan=false }) { return <Layout><main><Hero eyebrow={isPakistan ? 'PAKISTAN' : data.name.toUpperCase()} title={isPakistan ? 'Online Nikah in Pakistan' : `Online Nikah for residents of ${data.name}`} image={isPakistan ? '/hero-pakistan.png' : data.image} imageAlt={isPakistan ? 'A Pakistani Muslim couple signing a Nikah Nama' : `A modest Muslim couple preparing for a Nikah in ${data.name}`} actions={<><CTA href={whatsappLink()} children="Start with WhatsApp" /><CTA href="#details" outline children="Read the guide" /></>}><p>{isPakistan ? 'A careful, remote-first service for couples who need help understanding ceremony arrangements, eligibility, witnesses, documents and possible registration assistance.' : data.intro}</p></Hero><div id="details"><CountryBody data={data} isPakistan={isPakistan} /></div>{isPakistan && <PakistanCities />}</main></Layout> }

export function PakistanCities() { const cities = [['Karachi','A remote-first service for couples in Karachi, with city-specific contact support when you are ready to discuss dates, witnesses or documents.'],['Lahore','For Lahore enquiries, we can discuss the ceremony format and any Pakistan-based paperwork questions without implying that every step takes place in a local office.'],['Islamabad','Islamabad couples can start with a structured review of locations, identity documents, consent, witnesses and the intended use of any Nikah paperwork.'],['Rawalpindi','Rawalpindi enquiries are handled remotely, with the same careful separation of ceremony planning, registration assistance and overseas document use.'],['Faisalabad','For Faisalabad and surrounding areas, nationwide remote availability means you can ask about the process without travelling for an initial consultation.'],['Multan','Multan couples can share their proposed arrangements and receive guidance on what information to prepare before a ceremony is considered.'],['Hyderabad','Hyderabad enquiries can begin through WhatsApp, with practical questions about timing, witnesses, Mehr and any documents kept visible from the start.']]; return <section className="city-section"><div className="section-title"><p className="eyebrow">04 / Nationwide coverage</p><h2>Online Nikah services across Pakistan</h2><p className="section-lead">These are remote service areas, not a list of claimed physical offices. Contact us to confirm the current arrangement for your case.</p></div><div className="city-grid">{cities.map(([city, text]) => <article id={city.toLowerCase()} key={city}><div><span className="city-pin">{city.slice(0,1)}</span><h3>{city}</h3></div><p>{text}</p><a href={safeCityWhatsApp(city)}>Ask about {city} <span>↗</span></a></article>)}</div></section> }

// end
